### ISSUE TITLE
Change the type of coordinate playing Note blocks sounds

### ISSUE THREAD

**Issue by jupiter1390** [koca2000/NoteBlockAPI#19]
As currently sound is played in block based coordinates, which would cause sound playing on one side of speaker when player turns or moves slightly(due to 3D sound effect)

Change it into real time player based coordinate including decimal values so sounds can be played accurately without sound being played only on one side of headset

**Comment by koca2000** [comment]
Hi,
only SongPlayer that uses block based coordinates is NoteBlockSongPlayer. I can change it in this situation.

PositionSongPlayer uses exact Location specified by plugin developer including decimals.

RadioSongPlayer uses Player's eyes location which also is not block based according to my knowledge. 

Because Minecraft client has some issues with playing sounds in stereo on movement, new feature for RadioSongPlayer stereo sound was added in v1.2.3. It basicaly plays the sound two times with little offset to provide stereo sound.

Can you please specify more clearly in which case you have the problem?

**Comment by jupiter1390** [comment]
Oh, i meant NBSP, srry for lack of information
