### ISSUE TITLE
Tickrate and Octave range

### ISSUE THREAD

**Issue by Nipeno** [koca2000/NoteBlockAPI#35]
![image](https://user-images.githubusercontent.com/33656747/62000960-371a9880-b0e5-11e9-9dc1-727abe752f01.png)

I'm not 100% sure how the API works, but can it play songs at whatever tickrate or do I need to put it to one of the Minecraft defaults (which sound awful with this song) or can the API handle other tickrates?

Also can it handle sounds outside of the Minecraft octave range?

Because to me it seems like the Tickrate at 7.75 works, but the octave range doesn't but I just wanna make sure, because I want the music to sound as good as possible.

**Comment by Nipeno** [comment]
Asking, because on the "guide" on SpigotMC it says:

Convert .midi to .nbs 
Use Minecraft Note Block Studio:
https://github.com/HielkeMinecraft/OpenNoteBlockStudio/releases
1. import your .midi file to Note Block Studio;
2. save the file as .nbs file in your plugin folder

And doesn't mention the tickrate and octave at all, so I just want to make sure.

**Comment by koca2000** [comment]
Hi! NoteBlockAPI is very limited by Minecraft in octave range. Minecraft is changing pitch by speeding up the ogg sound file. NoteBlockAPI can't change that. The only way of using other octave range is to edit ogg files manually and create resourcepack.

NoteBlockAPI can handle any tempo. The error in OpenNoteBlockStudio is there because of DataPack export which is based on redstone.

**Comment by Nipeno** [comment]
Ok, thanks. Just wasn't sure how to make it sound best.
Have a nice day!
