### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by firewry** [koca2000/NoteBlockAPI#91]
the errors are:
package com.xxmicloxx.NoteBlockAPI.model does not exist
package com.xxmicloxx.NoteBlockAPI.songplayer does not exist
package com.xxmicloxx.NoteBlockAPI.utils does not exist
cannot find symbol

and the file does exist with the model file and all of that

**Comment by koca2000** [comment]
Hi! I would need some more information to be able to help you. Is this error in your IDE? How did you added the NoteBlockAPI to your project. Are you using Maven or Gradle?

**Comment by CerialPvP** [comment]
i am also getting this error, i am using maven but i added the dependency through intellij project structure since maven did not work for me, when i write the code in the ide it does not show any errors but once i compile the plugin it tells me the same things as the other guy

![image](https://user-images.githubusercontent.com/71380797/205514873-b86a1616-24ba-4457-9bc1-88f807625583.png)

![image](https://user-images.githubusercontent.com/71380797/205514892-8ce1476c-e00d-487a-a622-8d4fe4a79b6d.png)

![image](https://user-images.githubusercontent.com/71380797/205514918-2314ead4-24e1-4dc2-8460-081f5278d8c3.png)

**Comment by koca2000** [comment]
@CerialPvP In order to build your plugin with maven you have to add NoteBlockAPI as a maven dependency. Please make sure you added the Jitpack repository and you can ignore IntelliJ's error with `-SNAPSHOT` version. It is a symlink to the latest commit and therefore it is not in the manifest and IDE think it doesn't exists. The build should work. Alternatively use version `1.6.1`.

**Comment by CerialPvP** [comment]
Aight, I'll try that soon, I'll let you know how it goes
