### ISSUE TITLE
[Bug] Update error

### ISSUE THREAD

**Issue by craciu25yt** [koca2000/NoteBlockAPI#95]
In plugins.yml the version is `1.6.1-SNAPSHOT` but the version set in the plugin page is `1.6.1(MC1.8+)` so it always prompt the update warning

**Comment by koca2000** [comment]
Hi! Thank you for the report. I know about this issue. I accidentally uploaded the jar file with snapshot version instead of release version to spigot forums so the updater thinks there is a new release version. Since the version 1.6.1 was released two years ago, I won't make a new version just to fix this and instead I focus on version 2.0.
